### ISSUE TITLE
Review of content

### ISSUE THREAD

**Issue by pcmathias** [pcmathias/AACC-2019-Introduction-to-R#2]
Please use this issue to signal your review before I update the handouts on the AACC site

**Comment by jwrudolf** [comment]
Hi all. I went through the content tonight.  I think we are good and ready to update the handout.  Patrick many thanks for leading the effort (you have done the heavy lift on the course and are very much appreciated!).  I am really happy with where we are for content volume (I think we are in the 6 hour territory).  I didn't see any dead ends (where we relied on something that we hadn't previously created).  We have a few visual and structural inconsistencies (e.g. the way we use goals/objectives, some of the slide formatting, etc.) but that's all polish for a future iteration.  I bet we will find one or two things as we teach but think it is good to get a "finalized" deck out early to participants for download so my vote is to ship it to the printer.  See you guys this weekend!

**Comment by pcmathias** [comment]
I reviewed and agree that we have probably trimmed enough to get us down. I think we need to be conscious of time for each lesson. Lesson 4 is definitely the longest but we can get to halfway or more through that by lunch we will be in good shape.

**Comment by hermands** [comment]
Looks great!

- Some minor stuff in Transform: 
  -- Slide 46 "one" -> "on"
  -- Pipeline slide has funky formatting
- Add "What Else?" to Rmd's to demarcate the extra stuff?

**Comment by pcmathias** [comment]
Awesome, thanks for the input. I created the coursepack pdf. Please review your Rmd's and add a what else section if needed. Closing issue.
